### ISSUE TITLE
the size of this project is very small

### ISSUE THREAD

**Issue by hahakid** [RobustFieldAutonomyLab/jackal_dataset_20170608#1]
no matter using git clone or download the zip

**Comment by TixiaoShan** [comment]
Use git lfs

**Comment by TixiaoShan** [comment]
I will upload all the bags to Google Drive in the next day if you can wait.

**Comment by hahakid** [comment]
@TixiaoShan tks for your kind response, I am trying the LFS but the network not so well.

**Comment by TixiaoShan** [comment]
@ouyangkid I just updated the ReadMe file. You can find a Google Drive link in it.
